name: Seguridad OWASP

on:
  push:
    branches: [ master ]

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Ejecutar análisis de seguridad OWASP
      working-directory: "Práctica ED"
      run: mvn org.owasp:dependency-check-maven:check
